controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Controller definitions
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    bot_controller:
      type: diff_drive_controller/DiffDriveController

bot_controller:
  ros__parameters:
    # Wheel joints
    left_wheel_names: ['wheel_front_left_joint', 'wheel_back_left_joint']
    right_wheel_names: ['wheel_front_right_joint', 'wheel_back_right_joint']

    publish_rate: 50.0
    cmd_vel_timeout: 0.5

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    wheel_separation: 1.2
    wheel_radius: 0.28
    wheels_per_side: 2

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    use_stamped_vel: false
    base_frame_id: base_link

    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true